name: metpy-ams-2024
channels:
  - conda-forge
dependencies:
  - cartopy
  - dask
  - geopandas
  - jupyterlab
  - matplotlib
  - metpy
  - nc-time-axis
  - netcdf4
  - numpy
  - pythia-datasets
  - s3fs
  - siphon
  - xarray
  - zarr
